version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    container_name: backend
    ports:
      - '3000:3000'
    depends_on:
      - database

  database:
    image: postgres:13
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgressql/data
    ports:
      - '5433:5432'
